# Generated by Django 5.2.1 on 2025-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=64)),
                ('priority', models.CharField(max_length=15)),
                ('uploads', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('agent', models.CharField(max_length=200)),
                ('creationDateTime', models.DateTimeField()),
            ],
        ),
    ]
