# Generated by Django 5.2.1 on 2025-06-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creationDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
